# Site settings
title: foryou.blue
tag_text: foryou<span class="blue">.</span>blue
description: A blog about web development, blues and rock

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
